export const projects = [
  {
    id: 232,
    cover: "./images/kanban-preview.jpg",
    title: "Kanban App",
    tools: ["html", "css", "react", "redux"],
    netlify: "https://kanban-app-beka.netlify.app",
    github: "https://github.com/jalagania/kanban-app",
  },
  {
    id: 601,
    cover: "./images/feedback-preview.jpg",
    title: "Product Feedback App",
    tools: ["html", "css", "react", "redux"],
    netlify: "https://product-feedback-beka.netlify.app",
    github: "https://github.com/jalagania/product-feedback",
  },
  {
    id: 2801,
    cover: "./images/invoice-preview.jpg",
    title: "Invoice App",
    tools: ["html", "css", "react", "redux"],
    netlify: "https://invoice-app-beka.netlify.app",
    github: "https://github.com/jalagania/invoice-app",
  },
  {
    id: 304,
    cover: "./images/ecomm-preview.jpg",
    title: "E-commerce Web App",
    tools: ["html", "css", "react", "redux"],
    netlify: "https://audiophile-beka.netlify.app",
    github: "https://github.com/jalagania/audiophile-ecommerce",
  },
  {
    id: 1214,
    cover: "./images/entertainment-preview.jpg",
    title: "Entertainment Web App",
    tools: ["html", "css", "react", "context"],
    netlify: "https://entertainment-app-beka.netlify.app",
    github: "https://github.com/jalagania/entertainment-app",
  },
  {
    id: 1,
    cover: "./images/countries-preview.jpg",
    title: "REST Countries API",
    tools: ["html", "css", "react", "api"],
    netlify: "https://rest-countries-api-beka.netlify.app",
    github: "https://github.com/jalagania/rest-countries-api",
  },
  {
    id: 423,
    cover: "./images/memory-preview.jpg",
    title: "Memory Game",
    tools: ["html", "css", "ts", "react", "context"],
    netlify: "https://memory-game-beka.netlify.app",
    github: "https://github.com/jalagania/memory-game",
  },
  {
    id: 2,
    cover: "./images/comments-preview.jpg",
    title: "Interactive Comments",
    tools: ["html", "css", "react"],
    netlify: "https://interactive-comments-beka.netlify.app",
    github: "https://github.com/jalagania/interactive-comments",
  },
  {
    id: 3,
    cover: "./images/ttt-preview.jpg",
    title: "Tic Tac Toe",
    tools: ["html", "css", "react"],
    netlify: "https://tic-tac-toe-beka.netlify.app",
    github: "https://github.com/jalagania/tic-tac-toe",
  },
  {
    id: 4,
    cover: "./images/rps-preview.jpg",
    title: "Rock Paper Scissors +",
    tools: ["html", "css", "react"],
    netlify: "https://rock-paper-scissors-beka.netlify.app",
    github: "https://github.com/jalagania/rock-paper-scissors",
  },
  {
    id: 1216,
    cover: "./images/devjobs-preview.jpg",
    title: "Devjobs App",
    tools: ["html", "css", "react", "context"],
    netlify: "https://devjobs-app-beka.netlify.app",
    github: "https://github.com/jalagania/devjobs-app",
  },
  {
    id: 5,
    cover: "./images/multistep-preview.jpg",
    title: "Multi-step Form",
    tools: ["html", "tailwind", "react", "context"],
    netlify: "https://multistep-form-beka.netlify.app",
    github: "https://github.com/jalagania/multistep-form",
  },
  {
    id: 6,
    cover: "./images/calculator-preview.jpg",
    title: "PEMDAS Calculator",
    tools: ["html", "css", "react"],
    netlify: "https://pemdas-calculator-beka.netlify.app",
    github: "https://github.com/jalagania/pemdas-calculator",
  },
  {
    id: 7,
    cover: "./images/ecommerce-preview.jpg",
    title: "Ecommerce Product Page",
    tools: ["html", "css", "react"],
    netlify: "https://ecommerce-product-page-beka.netlify.app",
    github: "https://github.com/jalagania/ecommerce-product-page",
  },
  {
    id: 8,
    cover: "./images/joblist-preview.jpg",
    title: "Job List Filter",
    tools: ["html", "css", "react"],
    netlify: "https://job-list-filter-beka.netlify.app",
    github: "https://github.com/jalagania/job-list-filter",
  },
  {
    id: 415,
    cover: "./images/password-preview.jpg",
    title: "Password Generator",
    tools: ["html", "css", "ts", "react", "context"],
    netlify: "https://password-generator-beka.netlify.app",
    github: "https://github.com/jalagania/password-generator",
  },
  {
    id: 9,
    cover: "./images/todo-preview.jpg",
    title: "Todo List",
    tools: ["html", "css", "react"],
    netlify: "https://todo-list-beka.netlify.app",
    github: "https://github.com/jalagania/todo-list",
  },
  {
    id: 10,
    cover: "./images/crowdfund-preview.jpg",
    title: "Crowdfunding Page",
    tools: ["html", "tailwind", "react"],
    netlify: "https://crowdfunding-page-beka.netlify.app",
    github: "https://github.com/jalagania/crowdfunding-page",
  },
  {
    id: 11,
    cover: "./images/shortly-preview.jpg",
    title: "URL Shortener",
    tools: ["html", "css", "react", "api"],
    netlify: "https://url-shortener-beka.netlify.app",
    github: "https://github.com/jalagania/url-shortener",
  },
  {
    id: 505,
    cover: "./images/dashboard-preview.jpg",
    title: "SM Dashboard",
    tools: ["html", "css", "react"],
    netlify: "https://sm-dashboard-beka.netlify.app",
    github: "https://github.com/jalagania/sm-dashboard",
  },
  //   {
  //     id: 12,
  //     cover: "./images/ip-preview.jpg",
  //     title: "IP Address Tracker",
  //     tools: ["html", "css", "react"],
  //     netlify: "https://ip-address-tracker-beka.netlify.app",
  //     github: "https://github.com/jalagania/ip-address-tracker",
  //   },
  //   {
  //     id: 13,
  //     cover: "./images/card-preview.jpg",
  //     title: "Interactive Card",
  //     tools: ["html", "css", "react"],
  //     netlify: "https://interactive-schmard-beka.netlify.app",
  //     github: "https://github.com/jalagania/interactive-card",
  //   },
  //   {
  //     id: 14,
  //     cover: "./images/tip-preview.jpg",
  //     title: "Tip Calculator",
  //     tools: ["html", "css", "react"],
  //     netlify: "https://tip-calculator-beka.netlify.app",
  //     github: "https://github.com/jalagania/tip-calculator",
  //   },
  //   {
  //     id: 15,
  //     cover: "./images/timer-preview.jpg",
  //     title: "Countdown Timer",
  //     tools: ["html", "css", "react"],
  //     netlify: "https://countdown-timer-beka.netlify.app",
  //     github: "https://github.com/jalagania/countdown-timer",
  //   },
  //   {
  //     id: 16,
  //     cover: "./images/advice-preview.jpg",
  //     title: "Advice Generator",
  //     tools: ["html", "css", "react"],
  //     netlify: "https://advice-generator-beka.netlify.app",
  //     github: "https://github.com/jalagania/advice-generator",
  //   },
];
